# Generated by Django 6.0.1 on 2026-01-25 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0003_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('Electronics', 'ELECTRONICS'), ('Groceries', 'GROCERIES'), ('Clothings', 'CLOTHINGS')], max_length=15, null=True),
        ),
    ]
